name: acountmanager
description: "A new Flutter project."

publish_to: 'bazar'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  percent_indicator: ^3.0.1
  local_auth: ^2.1.1
  hive_generator: ^1.1.3
  shamsi_date: ^1.0.1
  dotted_border: ^2.0.0+2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  flutter_windowmanager: ^0.2.0
  adivery: ^4.2.0
  file_picker: ^8.0.6
  path_provider: ^2.0.11
  encrypt: ^5.0.1
  permission_handler: ^10.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/account/
    - assets/images/
    - assets/icons/


